name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2

      - name: 🔧 Install/Audit
        run: |
          yarn
          yarn audit

      - name: 👕 Lint
        run: yarn lint

      - name: 🏗️ Build
        run: |
          yarn clean
          yarn build

      - name: 🧪 Test
        run: yarn test

      - name: 📝 Document
        run: yarn doc

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs
